### ISSUE TITLE
Colors disappearing

### ISSUE THREAD

**Issue by adamsulimadolina** [ChrisKatsaras/react-nba-logos#3]
Hi,
I have following problem - if I'm using your package in multiple conponents, some elements just lose some colors. I don't know reason exactly, but I'm using switch statement to determine which of Logos component has to render. If I'm using constant rendering - this error doesn't appear. Is there anything I can do? 

EDIT - I figured out, that the problem is with useEffect with axios request - some logos just lose colors (Boston loses black, 76ers loses red). I don't know what to do.

**Comment by adamsulimadolina** [comment]
According to answer for my StackOverflow [post](https://stackoverflow.com/a/64849228/11213800) I changed IDs in all logos files (e.x. id: "A" to id: "A_BOS" for Boston Celtics). Seems to work now, so I'm closing Issue and creating pull request.

**Comment by robert-moore** [comment]
Running into the same problem even after the ID change. Any thoughts on direction to look into?

![image](https://user-images.githubusercontent.com/4934366/117633679-2df1a300-b176-11eb-9b4d-4f6f1788c138.png)
![image](https://user-images.githubusercontent.com/4934366/117633745-3ea21900-b176-11eb-989a-c77002a9a9f7.png)
