### ISSUE TITLE
Not able to install react dependency

### ISSUE THREAD

**Issue by cyoung43** [ChrisKatsaras/react-nba-logos#6]
Hi!

I'm trying to install react-nba-logos for a project but am getting errors when running `npm install react-nba-logos`.

This is some output from my terminal:

`Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/win32-x64-83_binding.node`
`Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/win32-x64-83_binding.node":`
`HTTP error 404 Not Found`

Any ideas for this?

**Comment by cyoung43** [comment]
This was just an issue on my end. I solved by using `npm install` on my wsl2.

**Comment by ChrisKatsaras** [comment]
Glad to hear you got things sorted out @cyoung43
